baseURL = 'https://hrideshmg.github.io/hugo-portfolio'
languageCode = 'en-us'
title = 'Portfolio'
theme = "nightfall"

[menu]
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "posts"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"

[params]
author = "Hridesh MG"
user = "home"
hostname = "hridesh"
[[params.social]]
key = 0
name = "github"
url = "https://github.com/hrideshmg"
[[params.social]]
key = 1
name = "instagram"
url = "https://www.instagram.com/hrideshmg/"
[[params.social]]
key = 2
name = "email"
url = "mailto:hridesh699@gmail.com"


